import type { Order } from "@/types/order";

export const dummyOrders: Order[] = [
  {
    id: "1042",
    customerName: "Amaya Fernando",
    item: "Ivory lace gown, custom",
    size: "Custom fit",
    total: "Rs 145,000",
    balanceDue: "Rs 45,000",
    placedDate: "Jun 18, 2026",
    status: "progress",
    statusLabel: "In progress",
    stages: [
      { label: "Fabric sourced", state: "done" },
      { label: "Pattern cut", state: "done" },
      { label: "Stitching — proposal submitted", state: "active" },
      { label: "Final fitting", state: "upcoming" },
    ],
  },
  {
    id: "1041",
    customerName: "Nadeesha Perera",
    item: "Bridesmaid rental, x3",
    size: "Mixed sizes",
    total: "Rs 36,000",
    balanceDue: "Rs 36,000",
    placedDate: "Jun 20, 2026",
    status: "pending",
    statusLabel: "Pending approval",
    stages: [
      { label: "Order received", state: "done" },
      { label: "Stock check", state: "active" },
      { label: "Fitting scheduled", state: "upcoming" },
      { label: "Ready for pickup", state: "upcoming" },
    ],
  },
  {
    id: "1038",
    customerName: "Kavindi Silva",
    item: "Custom veil",
    size: "One size",
    total: "Rs 18,500",
    balanceDue: "Rs 0",
    placedDate: "Jun 10, 2026",
    status: "completed",
    statusLabel: "Confirmed",
    stages: [
      { label: "Fabric sourced", state: "done" },
      { label: "Embroidery", state: "done" },
      { label: "Final QC", state: "done" },
      { label: "Delivered", state: "done" },
    ],
  },
];